repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        exclude: ^(docs/)|(project/)|(assignments/)|(project/interface/)

  - repo: local
    hooks:
      - id: python-tests
        name: Python unit tests
        entry: uv run pytest
        language: system
        types: [python]

      - id: cpp-tests
        name: C++ unit tests
        entry: uv run ctest --test-dir build --output-on-failure
        language: system
        types: [c]
