# ember/_core.pyi
# Type stubs for the C++ extension module _core

# Arithmetic operators
def mul(a: float, b: float) -> float: ...
def add(a: float, b: float) -> float: ...
def neg(a: float) -> float: ...
def id(a: float) -> float: ...
def inv(a: float) -> float: ...

# Comparison operators (return 0.0 or 1.0 as float)
def lt(a: float, b: float) -> float: ...
def eq(a: float, b: float) -> float: ...
def max(a: float, b: float) -> float: ...
def is_close(a: float, b: float, tol: float = ...) -> float: ...

# Non-linear activations
def sigmoid(a: float) -> float: ...
def relu(a: float) -> float: ...

# Exponential / logarithmic
def log(a: float) -> float: ...
def exp(a: float) -> float: ...
