# ember/_core_operators.pyi
# Type stubs for the C++ extension module _core

# Arithmetic operators
def _mul(a: float, b: float) -> float: ...
def _add(a: float, b: float) -> float: ...
def _neg(a: float) -> float: ...
def _id(a: float) -> float: ...
def _inv(a: float) -> float: ...

# Comparison operators (return 0.0 or 1.0 as float)
def _lt(a: float, b: float) -> float: ...
def _eq(a: float, b: float) -> float: ...
def _max(a: float, b: float) -> float: ...
def _is_close(a: float, b: float, tol: float = ...) -> float: ...

# Non-linear activations
def _sigmoid(a: float) -> float: ...
def _relu(a: float) -> float: ...

# Exponential / logarithmic
def _log(a: float) -> float: ...
def _exp(a: float) -> float: ...
