# ember/_core.pyi
# Type stubs for the C++ extension module _core

def mul(a: float, b: float) -> float: ...
def add(a: float, b: float) -> float: ...
def sub(a: float, b: float) -> float: ...
def div(a: float, b: float) -> float: ...
